In [1]:
import pandas as pd

In [2]:
from data_scraper.get_data_ch import *

D:\work\web_rag_agent\data_scraper\get_data_ch.py
D:\work\web_rag_agent
Loaded Environment Variables.

In [21]:
comp_name = "OXFORD RESOURCES"
comp_loc = "PANAMA"

In [22]:
kw, *args = comp_name.strip().lower().split()

In [23]:
kw

'oxford'

In [24]:
args

['resources']

In [25]:
# output_dir = os.getenv("OUTPUT_DIR")
search_df = search_all(kw)

https://api.company-information.service.gov.uk/search?q=oxford
<Response [200]>

In [26]:
search_df[["title","company_number","company_status","address.country"]].head()

,title,company_number,company_status,address.country
0,OXFORD LIMITED,02503801,active,NaN
1,OXFORD LIMITED PARTNERSHIP,LP015152,active,NaN
2,OXFORD RESOURCES SA,OE020907,registered,Panama
3,OXFORD LAND HOLDINGS LIMITED,OE016636,registered,"Virgin Islands, British"
4,OXFORD COMPANY SERVICES LTD,NaN,NaN,United Kingdom

In [40]:
def filter_company(df: pd.DataFrame, c_loc: str, *c_name_misc: str):
	tgt_headers = df['title'].str.lower().str.split(" ")
	req_cols = ["title","company_number","company_status","address.country"]
	mask = tgt_headers.apply(lambda words: any(arg in words for arg in c_name_misc))
	filtered_df = df[req_cols][mask]
	print(filtered_df.head())
	if c_loc:
		filtered_df = filtered_df[filtered_df["address.country"].str.lower() == c_loc.strip().lower()]
	# print(filtered_df.head())
	return filtered_df, df[req_cols]

In [41]:
filt_df, all_df = filter_company(search_df,comp_name, *args)

                 title company_number company_status address.country
2  OXFORD RESOURCES SA       OE020907     registered          Panama

In [44]:
search_df[search_df["address.country"].str.lower() == "Panama".lower()]

,date_of_creation,address_snippet,description,title,company_status,company_number,description_identifier,kind,snippet,company_type,...,address.locality,links.self,matches.snippet,address.premises,external_registration_number,address.country,address.region,appointment_count,description_identifiers,address.care_of
2,2023-01-31,"C/O Mendoza, Arias, Valle & Castillo Calle 50 ...",OE020907 - Registered on 31 January 2023,OXFORD RESOURCES SA,registered,OE020907,"[None, registered]",searchresults#company,,registered-overseas-entity,...,Panama City,/company/OE020907,[],"C/O Mendoza, Arias, Valle & Castillo Calle 50 ...",272184,Panama,NaN,NaN,NaN,NaN

In [35]:
filt_df.head()

Empty DataFrame
Columns: [title, company_number, company_status, address.country]
Index: []

In [36]:
filt_df

Empty DataFrame
Columns: [title, company_number, company_status, address.country]
Index: []

In [17]:
all_df.head()

,title,company_number,company_status,address.country
0,OXFORD LIMITED,02503801,active,NaN
1,OXFORD LIMITED PARTNERSHIP,LP015152,active,NaN
2,OXFORD RESOURCES SA,OE020907,registered,Panama
3,OXFORD LAND HOLDINGS LIMITED,OE016636,registered,"Virgin Islands, British"
4,OXFORD HOMES (DEVELOPMENT) LIMITED,NaN,NaN,England